import Link from "next/link";
import { getSources, getTopics } from "@/lib/api";
import { EmptyState, Notice, PageShell } from "@/components/site";

export default async function Home() {
  const [topics, sources] = await Promise.all([getTopics(), getSources()]);
  return <PageShell>
    <section className="paper-grid border-b border-[var(--line)]">
      <div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.35fr_.65fr] lg:px-8 lg:py-24">
        <div><p className="eyebrow">Independent public-ideas archive · Collection 01</p><h1 className="mt-5 max-w-4xl text-5xl leading-[1.02] md:text-7xl">Ideas are easier to understand when the <em className="text-[var(--forest)]">evidence stays visible.</em></h1><p className="mt-7 max-w-2xl text-xl leading-8 text-[var(--muted)]">Explore the public record of African founders through dated sources, speaker-aware transcripts, and citation-grounded research answers.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/ask" className="rounded-full bg-[var(--forest)] px-6 py-3 font-bold text-white no-underline">Ask the collection →</Link><Link href="/sources" className="rounded-full border border-[var(--line)] bg-white px-6 py-3 font-bold no-underline">Browse evidence</Link></div></div>
        <div className="self-end rounded-2xl border border-[var(--line)] bg-[var(--card)] p-6 shadow-[0_18px_60px_rgba(23,33,28,.08)]"><p className="eyebrow">Now cataloguing</p><h2 className="mt-4 text-3xl leading-tight">The Iyinoluwa Aboyeji Public Ideas Collection</h2><div className="my-6 h-px bg-[var(--line)]"/><dl className="grid grid-cols-2 gap-5"><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Approved records</dt><dd className="serif mt-1 text-3xl">{sources.length}</dd></div><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Research topics</dt><dd className="serif mt-1 text-3xl">{topics.length}</dd></div></dl><p className="mt-6 text-sm leading-6 text-[var(--muted)]">Independent and not endorsed. Sources require human approval before appearing in answers.</p></div>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Notice /><div className="mt-16 grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">A research instrument</p><h2 className="mt-3 text-4xl">Not a personality simulator.</h2><p className="prose-copy mt-5">The assistant answers only from approved Tier A and Tier B evidence. It shows dates, short excerpts, and direct links—and refuses when the archive cannot support a conclusion.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01","Evidence before inference","Raw snapshots are preserved before cleaning or classification."],["02","Attribution before answers","Interviewers, hosts, and panelists are kept distinct from the founder."],["03","Uncertainty stays visible","Conflicts, sparse evidence, and changes over time are reported carefully."]].map(([n,t,c])=><article key={n} className="rounded-xl border border-[var(--line)] bg-[var(--card)] p-5"><span className="serif text-3xl text-[var(--ochre)]">{n}</span><h3 className="mt-8 text-xl">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{c}</p></article>)}</div></div></section>
    <section className="bg-[var(--forest)] text-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b9d2c3]">Explore the index</p><h2 className="mt-3 text-4xl">Browse by research topic</h2></div><Link href="/topics" className="font-bold text-white">All topics →</Link></div>{topics.length ? <div className="mt-8 flex flex-wrap gap-3">{topics.slice(0,12).map(topic=><Link key={topic.id} href={`/topics/${topic.slug}`} className="rounded-full border border-white/25 px-4 py-2 text-sm no-underline hover:bg-white hover:text-[var(--forest)]">{topic.name}</Link>)}</div> : <p className="mt-8 text-[#cadcd0]">Topic taxonomy appears after the seed command runs.</p>}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Latest evidence</p><h2 className="mt-2 text-4xl">Recently approved sources</h2></div><Link href="/sources" className="font-bold text-[var(--forest)]">Open library →</Link></div>{sources.length ? <div className="mt-8 divide-y divide-[var(--line)] border-y border-[var(--line)]">{sources.slice(0,4).map(source=><Link href={`/sources/${source.id}`} key={source.id} className="grid gap-3 py-6 no-underline md:grid-cols-[110px_1fr_180px]"><span className="eyebrow">Tier {source.source_tier} · {source.content_type}</span><strong className="serif text-xl">{source.title}</strong><span className="text-sm text-[var(--muted)]">{source.publisher ?? "Publisher unknown"}<br/>{source.publication_date ?? "Date unknown"}</span></Link>)}</div> : <div className="mt-8"><EmptyState title="The reviewed shelves are empty" copy="Run migrations and seed data, then approve genuine candidates or import lawful source material. No fictional statement is attributed to a real founder." /></div>}</section>
  </PageShell>;
}
