"use client";
import Link from "next/link";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api/v1";
export function AdminShell({title,copy,children}:{title:string;copy:string;children:ReactNode}){const links=[["Overview","/admin"],["Candidates","/admin/candidates"],["Jobs","/admin/jobs"],["Sources","/admin/sources"],["Chunks","/admin/chunks"],["Analytics","/admin/analytics"],["Evaluations","/admin/evaluations"],["Costs","/admin/costs"]] as const;return <div className="min-h-screen bg-[#f4f2ec]"><header className="border-b border-[var(--line)] bg-[#163f30] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="serif text-xl no-underline">African Founder Studies</Link><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-wider">Research administration</span></div></header><div className="mx-auto grid max-w-7xl gap-8 px-5 py-8 lg:grid-cols-[210px_1fr]"><nav aria-label="Admin" className="flex gap-2 overflow-auto lg:flex-col">{links.map(([label,href])=><Link href={href} key={href} className="whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold no-underline hover:bg-white">{label}</Link>)}</nav><main><p className="eyebrow">Control room</p><h1 className="mt-2 text-4xl">{title}</h1><p className="mt-3 max-w-3xl leading-7 text-[var(--muted)]">{copy}</p><div className="mt-8">{children}</div></main></div></div>}

export function LoginForm(){const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);try{const response=await fetch(`${API}/auth/login`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});const data=await response.json() as {csrf_token?:string;error?:{message:string}};if(!response.ok)throw new Error(data.error?.message??"Login failed");if(data.csrf_token)sessionStorage.setItem("afs_csrf",data.csrf_token);window.location.href="/admin"}catch(reason){setError(reason instanceof Error?reason.message:"Login failed")}finally{setLoading(false)}}return <form onSubmit={submit} className="grid gap-5"><label className="grid gap-2 font-bold">Email<input name="email" type="email" required autoComplete="username" className="rounded-md border border-[var(--line)] p-3"/></label><label className="grid gap-2 font-bold">Password<input name="password" type="password" required minLength={12} autoComplete="current-password" className="rounded-md border border-[var(--line)] p-3"/></label>{error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={loading} className="rounded-full bg-[var(--forest)] px-5 py-3 font-bold text-white">{loading?"Authenticating…":"Sign in securely"}</button></form>}

type Candidate={id:string;title:string;publisher:string|null;normalized_url:string;score:number;score_breakdown:Record<string,number>;robots_status:string;status:string};
export function CandidateQueue(){const [items,setItems]=useState<Candidate[]>([]);const [state,setState]=useState("Loading review queue…");async function load(){try{const r=await fetch(`${API}/candidates?status=pending`,{credentials:"include"});if(r.status===401){setState("Sign in to load the protected review queue.");return}const data=await r.json() as Candidate[];setItems(data);setState(data.length?"":"No pending candidates.")}catch{setState("The API is unavailable.")}}useEffect(()=>{void load()},[]);async function review(id:string,decision:"approved"|"rejected"){const note=window.prompt(`Review note for ${decision}:`);if(!note)return;const r=await fetch(`${API}/candidates/${id}/review`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":sessionStorage.getItem("afs_csrf")??""},body:JSON.stringify({decision,note,source_tier:decision==="approved"?"B":"D"})});if(r.ok)await load();else setState("Review failed. Refresh the session and try again.")}return <div>{state&&<p className="rounded-xl border border-[var(--line)] bg-white p-5 text-[var(--muted)]">{state}</p>}<div className="grid gap-4">{items.map(item=><article key={item.id} className="rounded-xl border border-[var(--line)] bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><span className="eyebrow">Score {item.score} · Robots {item.robots_status}</span><h2 className="mt-2 text-2xl">{item.title}</h2><a href={item.normalized_url} target="_blank" rel="noreferrer" className="mt-2 block break-all text-sm text-[var(--forest)]">{item.normalized_url}</a><p className="mt-2 text-sm text-[var(--muted)]">{item.publisher??"Publisher unknown"}</p></div><div className="flex items-start gap-2"><button onClick={()=>void review(item.id,"rejected")} className="rounded-full border border-red-700 px-4 py-2 text-sm font-bold text-red-800">Reject</button><button onClick={()=>void review(item.id,"approved")} className="rounded-full bg-[var(--forest)] px-4 py-2 text-sm font-bold text-white">Approve</button></div></div><details className="mt-5"><summary className="cursor-pointer text-sm font-bold">Explain score</summary><dl className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{Object.entries(item.score_breakdown).map(([key,value])=><div key={key} className="rounded bg-[#f4f2ec] p-2"><dt>{key.replaceAll("_"," ")}</dt><dd className="font-bold">{value}</dd></div>)}</dl></details></article>)}</div></div>}

export function ProtectedData({endpoint}:{endpoint:string}){const [data,setData]=useState<unknown>(null);const [error,setError]=useState("");useEffect(()=>{fetch(`${API}/${endpoint}`,{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error(r.status===401?"Sign in to view protected data.":"Request failed.");setData(await r.json())}).catch((e:unknown)=>setError(e instanceof Error?e.message:"Request failed."))},[endpoint]);if(error)return <p className="rounded-xl border border-amber-300 bg-amber-50 p-5">{error}</p>;if(!data)return <p className="rounded-xl border border-[var(--line)] bg-white p-5">Loading…</p>;return <pre className="max-h-[620px] overflow-auto rounded-xl bg-[#17211c] p-5 text-xs leading-6 text-[#d8e7de]">{JSON.stringify(data,null,2)}</pre>}
